/****************************************************************************
 *
 *   Copyright (C) 2021-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/


#pragma once

#include <stddef.h>

#include <uORB/uORB.h>

static constexpr size_t ORB_TOPICS_COUNT{283};
static constexpr size_t orb_topics_count() { return ORB_TOPICS_COUNT; }

/*
 * Returns array of topics metadata
 */
extern const struct orb_metadata *const *orb_get_topics() __EXPORT;

enum class ORB_ID : orb_id_size_t {
	action_request = 0,
	actuator_armed = 1,
	actuator_controls_status_0 = 2,
	actuator_controls_status_1 = 3,
	actuator_motors = 4,
	actuator_outputs = 5,
	actuator_outputs_debug = 6,
	actuator_outputs_sim = 7,
	actuator_servos = 8,
	actuator_servos_trim = 9,
	actuator_test = 10,
	adc_report = 11,
	airspeed = 12,
	airspeed_validated = 13,
	airspeed_wind = 14,
	arming_check_reply = 15,
	arming_check_request = 16,
	autotune_attitude_control_status = 17,
	aux_global_position = 18,
	battery_status = 19,
	button_event = 20,
	camera_capture = 21,
	camera_status = 22,
	camera_trigger = 23,
	can_interface_status = 24,
	cellular_status = 25,
	collision_constraints = 26,
	collision_report = 27,
	config_control_setpoints = 28,
	config_overrides = 29,
	config_overrides_request = 30,
	control_allocator_status = 31,
	cpuload = 32,
	dataman_request = 33,
	dataman_response = 34,
	debug_array = 35,
	debug_key_value = 36,
	debug_value = 37,
	debug_vect = 38,
	differential_drive_control_output = 39,
	differential_drive_setpoint = 40,
	differential_pressure = 41,
	distance_sensor = 42,
	ekf2_timestamps = 43,
	esc_report = 44,
	esc_status = 45,
	estimator_aid_src_airspeed = 46,
	estimator_aid_src_aux_global_position = 47,
	estimator_aid_src_aux_vel = 48,
	estimator_aid_src_baro_hgt = 49,
	estimator_aid_src_drag = 50,
	estimator_aid_src_ev_hgt = 51,
	estimator_aid_src_ev_pos = 52,
	estimator_aid_src_ev_vel = 53,
	estimator_aid_src_ev_yaw = 54,
	estimator_aid_src_fake_hgt = 55,
	estimator_aid_src_fake_pos = 56,
	estimator_aid_src_gnss_hgt = 57,
	estimator_aid_src_gnss_pos = 58,
	estimator_aid_src_gnss_vel = 59,
	estimator_aid_src_gnss_yaw = 60,
	estimator_aid_src_gravity = 61,
	estimator_aid_src_mag = 62,
	estimator_aid_src_optical_flow = 63,
	estimator_aid_src_rng_hgt = 64,
	estimator_aid_src_sideslip = 65,
	estimator_aid_src_terrain_optical_flow = 66,
	estimator_aid_src_terrain_range_finder = 67,
	estimator_attitude = 68,
	estimator_baro_bias = 69,
	estimator_bias3d = 70,
	estimator_ev_pos_bias = 71,
	estimator_event_flags = 72,
	estimator_global_position = 73,
	estimator_gnss_hgt_bias = 74,
	estimator_gps_status = 75,
	estimator_innovation_test_ratios = 76,
	estimator_innovation_variances = 77,
	estimator_innovations = 78,
	estimator_local_position = 79,
	estimator_odometry = 80,
	estimator_optical_flow_vel = 81,
	estimator_rng_hgt_bias = 82,
	estimator_selector_status = 83,
	estimator_sensor_bias = 84,
	estimator_states = 85,
	estimator_status = 86,
	estimator_status_flags = 87,
	estimator_wind = 88,
	event = 89,
	external_ins_attitude = 90,
	external_ins_global_position = 91,
	external_ins_local_position = 92,
	failsafe_flags = 93,
	failure_detector_status = 94,
	figure_eight_status = 95,
	flaps_setpoint = 96,
	flight_phase_estimation = 97,
	follow_target = 98,
	follow_target_estimator = 99,
	follow_target_status = 100,
	fw_virtual_attitude_setpoint = 101,
	generator_status = 102,
	geofence_result = 103,
	geofence_status = 104,
	gimbal_controls = 105,
	gimbal_device_attitude_status = 106,
	gimbal_device_information = 107,
	gimbal_device_set_attitude = 108,
	gimbal_manager_information = 109,
	gimbal_manager_set_attitude = 110,
	gimbal_manager_set_manual_control = 111,
	gimbal_manager_status = 112,
	gimbal_v1_command = 113,
	goto_setpoint = 114,
	gpio_config = 115,
	gpio_in = 116,
	gpio_out = 117,
	gpio_request = 118,
	gps_dump = 119,
	gps_inject_data = 120,
	gripper = 121,
	health_report = 122,
	heater_status = 123,
	home_position = 124,
	hover_thrust_estimate = 125,
	input_rc = 126,
	internal_combustion_engine_status = 127,
	iridiumsbd_status = 128,
	irlock_report = 129,
	landing_gear = 130,
	landing_gear_wheel = 131,
	landing_target_innovations = 132,
	landing_target_pose = 133,
	launch_detection_status = 134,
	led_control = 135,
	log_message = 136,
	logger_status = 137,
	mag_worker_data = 138,
	magnetometer_bias_estimate = 139,
	manual_control_input = 140,
	manual_control_setpoint = 141,
	manual_control_switches = 142,
	mavlink_log = 143,
	mavlink_tunnel = 144,
	mc_virtual_attitude_setpoint = 145,
	message_format_request = 146,
	message_format_response = 147,
	mission = 148,
	mission_result = 149,
	mode_completed = 150,
	mount_orientation = 151,
	navigator_mission_item = 152,
	npfg_status = 153,
	obstacle_distance = 154,
	obstacle_distance_fused = 155,
	offboard_control_mode = 156,
	onboard_computer_status = 157,
	orb_multitest = 158,
	orb_test = 159,
	orb_test_large = 160,
	orb_test_medium = 161,
	orb_test_medium_multi = 162,
	orb_test_medium_queue = 163,
	orb_test_medium_queue_poll = 164,
	orb_test_medium_wrap_around = 165,
	orbit_status = 166,
	parameter_primary_set_value_request = 167,
	parameter_primary_set_value_response = 168,
	parameter_remote_set_value_request = 169,
	parameter_remote_set_value_response = 170,
	parameter_reset_request = 171,
	parameter_set_used_request = 172,
	parameter_set_value_request = 173,
	parameter_set_value_response = 174,
	parameter_update = 175,
	ping = 176,
	position_controller_landing_status = 177,
	position_controller_status = 178,
	position_setpoint = 179,
	position_setpoint_triplet = 180,
	power_button_state = 181,
	power_monitor = 182,
	pps_capture = 183,
	pwm_input = 184,
	px4io_status = 185,
	qshell_req = 186,
	qshell_retval = 187,
	radio_status = 188,
	rate_ctrl_status = 189,
	rc_channels = 190,
	rc_parameter_map = 191,
	register_ext_component_reply = 192,
	register_ext_component_request = 193,
	rpm = 194,
	rtl_status = 195,
	rtl_time_estimate = 196,
	safety_button = 197,
	satellite_info = 198,
	sensor_accel = 199,
	sensor_accel_fifo = 200,
	sensor_airflow = 201,
	sensor_baro = 202,
	sensor_combined = 203,
	sensor_correction = 204,
	sensor_gnss_relative = 205,
	sensor_gps = 206,
	sensor_gyro = 207,
	sensor_gyro_fft = 208,
	sensor_gyro_fifo = 209,
	sensor_hygrometer = 210,
	sensor_mag = 211,
	sensor_optical_flow = 212,
	sensor_preflight_mag = 213,
	sensor_selection = 214,
	sensor_uwb = 215,
	sensors_status_baro = 216,
	sensors_status_imu = 217,
	sensors_status_mag = 218,
	spoilers_setpoint = 219,
	system_power = 220,
	takeoff_status = 221,
	task_stack_info = 222,
	tecs_status = 223,
	telemetry_status = 224,
	tiltrotor_extra_controls = 225,
	timesync_status = 226,
	trajectory_bezier = 227,
	trajectory_setpoint = 228,
	trajectory_waypoint = 229,
	transponder_report = 230,
	tune_control = 231,
	uavcan_parameter_request = 232,
	uavcan_parameter_value = 233,
	ulog_stream = 234,
	ulog_stream_ack = 235,
	unregister_ext_component = 236,
	vehicle_acceleration = 237,
	vehicle_air_data = 238,
	vehicle_angular_acceleration_setpoint = 239,
	vehicle_angular_velocity = 240,
	vehicle_angular_velocity_groundtruth = 241,
	vehicle_attitude = 242,
	vehicle_attitude_groundtruth = 243,
	vehicle_attitude_setpoint = 244,
	vehicle_command = 245,
	vehicle_command_ack = 246,
	vehicle_command_mode_executor = 247,
	vehicle_constraints = 248,
	vehicle_control_mode = 249,
	vehicle_global_position = 250,
	vehicle_global_position_groundtruth = 251,
	vehicle_gps_position = 252,
	vehicle_imu = 253,
	vehicle_imu_status = 254,
	vehicle_land_detected = 255,
	vehicle_local_position = 256,
	vehicle_local_position_groundtruth = 257,
	vehicle_local_position_setpoint = 258,
	vehicle_magnetometer = 259,
	vehicle_mocap_odometry = 260,
	vehicle_odometry = 261,
	vehicle_optical_flow = 262,
	vehicle_optical_flow_vel = 263,
	vehicle_rates_setpoint = 264,
	vehicle_roi = 265,
	vehicle_status = 266,
	vehicle_thrust_setpoint = 267,
	vehicle_thrust_setpoint_virtual_fw = 268,
	vehicle_thrust_setpoint_virtual_mc = 269,
	vehicle_torque_setpoint = 270,
	vehicle_torque_setpoint_virtual_fw = 271,
	vehicle_torque_setpoint_virtual_mc = 272,
	vehicle_trajectory_bezier = 273,
	vehicle_trajectory_waypoint = 274,
	vehicle_trajectory_waypoint_desired = 275,
	vehicle_visual_odometry = 276,
	velocity_limits = 277,
	voxl2_io_data = 278,
	vtol_vehicle_status = 279,
	wheel_encoders = 280,
	wind = 281,
	yaw_estimator_status = 282,

	INVALID
};

const struct orb_metadata *get_orb_meta(ORB_ID id);
