# Install script for directory: /home/cpsl/PX4-Autopilot_1.15.4

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "MinSizeRel")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set path to fallback-tool for dependency-resolution.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/arm-none-eabi-objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/platforms/nuttx/src/px4/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/adc/ads1115/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/adc/board_adc/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/bmp280/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/bmp388/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/dps310/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/goertek/spa06/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/goertek/spl06/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/invensense/icp101xx/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/invensense/icp201xx/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/lps22hb/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/lps33hw/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/maiertek/mpc2520/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/barometer/ms5611/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/batt_smbus/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/camera_capture/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/camera_trigger/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/cdcacm_autostart/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/differential_pressure/ms4525do/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/differential_pressure/ms5525dso/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/differential_pressure/sdp3x/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/cm8jl65/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/gy_us42/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/leddar_one/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/lightware_laser_i2c/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/lightware_laser_serial/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/ll40ls/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/mb12xx/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/srf02/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/teraranger/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/tf02pro/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/tfmini/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/ulanding_radar/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/vl53l0x/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/distance_sensor/vl53l1x/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/dshot/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/gnss/septentrio/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/gps/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/heater/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/imu/analog_devices/adis16448/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/imu/invensense/mpu6000/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/ins/vectornav/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/irlock/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/lights/rgbled/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/lights/rgbled_is31fl3195/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/lights/rgbled_lp5562/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/lights/rgbled_ncp5623c/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/akm/ak09916/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/akm/ak8963/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/bosch/bmm150/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/hmc5883/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/isentek/ist8308/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/isentek/ist8310/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/lis3mdl/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/lsm303agr/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/memsic/mmc5983ma/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/qmc5883l/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/rm3100/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/st/iis2mdc/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/magnetometer/vtrantech/vcm1193l/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/optical_flow/paa3905/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/optical_flow/paw3902/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/optical_flow/pmw3901/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/optical_flow/px4flow/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/optical_flow/thoneflow/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/pca9685_pwm_out/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/pwm_input/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/pwm_out/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/px4io/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/smart_battery/batmon/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/telemetry/bst/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/telemetry/frsky_telemetry/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/telemetry/hott/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/tone_alarm/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/drivers/uavcan/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/airspeed_selector/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/attitude_estimator_q/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/battery_status/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/camera_feedback/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/commander/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/control_allocator/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/dataman/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/ekf2/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/esc_battery/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/events/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/flight_mode_manager/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/fw_att_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/fw_autotune_attitude_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/fw_pos_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/fw_rate_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/gimbal/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/gyro_calibration/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/gyro_fft/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/land_detector/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/landing_target_estimator/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/load_mon/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/local_position_estimator/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/logger/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/mag_bias_estimator/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/manual_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/mavlink/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/mc_att_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/mc_autotune_attitude_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/mc_hover_thrust_estimator/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/mc_pos_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/mc_rate_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/navigator/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/rc_update/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/rover_pos_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/sensors/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/simulation/pwm_out_sim/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/simulation/sensor_baro_sim/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/simulation/sensor_gps_sim/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/simulation/sensor_mag_sim/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/simulation/simulator_sih/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/temperature_compensation/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/uuv_att_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/uuv_pos_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/uxrce_dds_client/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/modules/vtol_att_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/actuator_test/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/bl_update/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/bsondump/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/dumpfile/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/gpio/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/hardfault_log/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/i2cdetect/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/led_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/mft/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/mtd/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/nshterm/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/param/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/perf/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/reboot/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/reflect/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/sd_bench/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/sd_stress/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/serial_test/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/system_time/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/top/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/topic_listener/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/tune_control/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/uorb/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/usb_connected/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/ver/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/systemcmds/work_queue/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/src/examples/fake_gps/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/boards/px4/fmu-v3/src/cmake_install.cmake")
  include("/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/platforms/nuttx/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
if(CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_COMPONENT MATCHES "^[a-zA-Z0-9_.+-]+$")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
  else()
    string(MD5 CMAKE_INST_COMP_HASH "${CMAKE_INSTALL_COMPONENT}")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INST_COMP_HASH}.txt")
    unset(CMAKE_INST_COMP_HASH)
  endif()
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/home/cpsl/PX4-Autopilot_1.15.4/build/px4_fmu-v3_default/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
